<?php
// $Id$

/**
 * @file
 * Provides the Direct Deposit payment method.
 */

 

function tilers_direct_deposit_uc_invoice_templates() {
  return array('direct-deposit');
}
 
function tilers_direct_deposit_order($op, &$arg1, $arg2) {
  switch ($op) {
    case 'save':
    break;
    case 'submit':
    break;
  }
}
 
 
/**
 * Implementation of hook_menu().
 */
function tilers_direct_deposit_menu() {
  $items['admin/store/orders/%uc_order/receive_directdeposit'] = array(
    'title' => 'Receive Direct Deposit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tilers_direct_deposit_receive_directdeposit_form', 3),
    'access arguments' => array('view all orders'),
    'type' => MENU_CALLBACK,
    'file' => 'tilers_direct_deposit.admin.inc',
  );
  return $items;
}

function tilers_direct_deposit_theme() {
  return array(
    'tilers_direct_deposit_receive_directdeposit_form' => array(
      'arguments' => array('form' => NULL),
      'file' => 'tilers_direct_deposit.admin.inc',
    ),
  );
}

/**
 * Implementation of hook_payment_method().
 */
function tilers_direct_deposit_payment_method() {
  $methods[] = array(
    'id' => 'directdeposit',
    'name' => t('Direct Deposit'),
    'title' => t('Direct Deposit'),
    'desc' => t('Pay by Direct Deposit.'),
    'callback' => 'tilers_payment_method_directdeposit',
    'weight' => 1,
    'directdepositout' => TRUE,
    'no_gateway' => TRUE,
  );
  return $methods;
}


/**
 * Handle the Direct Deposit payment method.
 */
function tilers_payment_method_directdeposit($op, &$arg1) {
  switch ($op) {
    case 'cart-details':

        /*$details = t('Direct Deposit to:') .'<p><pre>'.
                   variable_get('cosmic_directdeposit_account_name', '') .'<br />'.
                   t('BSB:     ') . variable_get('cosmic_directdeposit_account_bsb', '') .'<br />'.
                   t('Account: ') . variable_get('cosmic_directdeposit_account_number', '') .'<br />'.
                   t('Bank:    '). variable_get('cosmic_directdeposit_account_bank', '') .'<br />'.
                   '</p><p>'. variable_get('cosmic_directdeposit_policy', '') .'</p></pre>';
        return $details;*/
      return '<p class="important-message">You will receive the bank detail by mail</p>';

    // We don't want to display account information on order review
    /*case 'cart-review':
        $review[] = array('title' => t('Direct Deposit to'), 'data' => '<p>'.
            variable_get('cosmic_directdeposit_account_name', '') .'<br />'.
            t('BSB: '). variable_get('cosmic_directdeposit_account_bsb', '') .'<br />'.
            t('Account: '). variable_get('cosmic_directdeposit_account_number', '') .'<br />'.
            t('Bank: '). variable_get('cosmic_directdeposit_account_bank', '') .'<br />'.
            '</p><p>'. variable_get('cosmic_directdeposit_policy', '') .'</p>');
    return $review;*/

    case 'order-view':
      if (!variable_get('uc_payment_tracking', TRUE)) {
        return '';
      }
      $result = db_query("SELECT clear_date FROM {tilers_payment_directdeposit} WHERE "
                        ."order_id = %d ", $arg1->order_id);
      if ($directdeposit = db_fetch_object($result)) {
        $output = t('Clear Date:') .' '. format_date($directdeposit->clear_date, 'custom', variable_get('uc_date_format_default', 'd/m/Y'));
      }
      else {
        $output = l(t('Receive Direct Deposit'), 'admin/store/orders/'. $arg1->order_id .'/receive_directdeposit');
      }
      $output .= '<br />';
      return $output;

    case 'customer-view':
      if (!variable_get('uc_payment_tracking', TRUE)) {
        return '';
      }
      $result = db_query("SELECT clear_date FROM {tilers_payment_directdeposit} WHERE "
                        ."order_id = %d ", $arg1->order_id);
      if ($directdeposit = db_fetch_object($result)) {
        $output = t('Direct Deposit received') .'<br />'
                . t('Expected clear date:') .'<br />'. format_date($directdeposit->clear_date, 'custom', variable_get('uc_date_format_default', 'd/m/Y'));
      }
      return $output;

    case 'settings':
      $form['directdeposit_address_info'] = array(
        '#value' => '<div>'. t('Enter the bank account details to display to customers who choose this payment method during checkout.') .'</div>',
      );

      $form['tilers_directdeposit_account_name'] = uc_textfield(t('Account Name'), variable_get('tilers_directdeposit_account_name', ''), FALSE, t('Direct Deposit bank account name.'), 128);
      $form['tilers_directdeposit_account_bsb'] = uc_textfield(t('BSB'), variable_get('tilers_directdeposit_account_bsb', ''), FALSE, NULL, 128);
      $form['tilers_directdeposit_account_number'] = uc_textfield(t('Account Number'), variable_get('tilers_directdeposit_account_number', ''), FALSE, NULL, 128);
      $form['tilers_directdeposit_account_bank'] = uc_textfield(t('Bank Name'), variable_get('tilers_directdeposit_account_bank', ''), FALSE);

      $form['tilers_directdeposit_policy'] = array(
        '#type' => 'textarea',
        '#title' => t('Direct Deposit payment instructions'),
        '#description' => t('Instructions for customers on the checkout page.'),
        '#default_value' => variable_get('tilerscos_directdeposit_policy', 'Please note: Direct Deposit details will not be displayed after checkout.'),
        '#rows' => 3,
      );
      return $form;
  }
}

