<?php 

function trp_theme($existing, $type, $theme, $path) {
  return array(
    'display_trp' => array(
      'arguments' => array('products' => NULL),
      'template' => 'display-trp'
    ), 
  );
}

function trp_get_products($nids){
    
    $products = array();
    
    if (!empty($nids)){
      $count = 0;
        foreach ($nids as $nid){
            $node = node_load($nid['nid']);
            if (is_object($node)){
              $count++;
              $products[] = $node;
            }
            if ($count == 4) { break; }
        }
    
    }
    return $products;
}
